#!/bin/bash
# complete_vault.sh - Automates the setup of the rhncrs-collab Obsidian Vault
# Generated by Gemini, Executed by Claude

# --- Configuration ---
VAULT_ROOT="/Users/hoe/Library/Mobile Documents/iCloud~md~obsidian/Documents/rhncrs-collab"
SOURCE_ROOT="/Users/hoe/Dev/org"

# Project Mapping (ID_Name SourceDir)
declare -a PROJECTS=(
    "11_Rhinoceros_Music rhinoceros-music"
    "12_Rhinocrash rhinocrash"
    "13_Rhncrs_V1 rhncrsv1"
    "14_Infrastructure infrastructure"
    "15_Infra_Swarm infrastructure-swarm"
)

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log() { echo -e "${BLUE}[GEMINI-SCRIPT]${NC} $1"; }
success() { echo -e "${GREEN}✓ $1${NC}"; }

# --- 1. Verify Access ---
log "Verifying vault access..."
if [ ! -d "$VAULT_ROOT" ]; then
    echo "Error: Vault root not found at $VAULT_ROOT"
    exit 1
fi

# --- 2. Create Directory Structure ---
log "Creating directory structure..."
DIRS=(
    "20_Domains/21_Audio_Engineering"
    "20_Domains/22_AI_Systems"
    "20_Domains/23_DevOps"
    "20_Domains/24_Business_Admin"
    "30_Resources/Manuals"
    "30_Resources/API_Docs"
    "30_Resources/Assets"
    "40_Logs/Daily_Notes"
    "40_Logs/Meeting_Notes"
    "40_Logs/Incident_Reports"
)

for dir in "${DIRS[@]}"; do
    mkdir -p "$VAULT_ROOT/$dir"
done
success "Directories created."

# --- 3. Create Templates ---
log "Generating templates..."

# Technical Spec Template
cat <<'EOF' > "$VAULT_ROOT/90_Admin/Templates/Technical-Spec.md"
---
created: {{date}}
updated: {{date}}
tags: [#type/spec, #domain/xxx]
status: draft
---

# Technical Specification: {{title}}

## Overview
Brief description of the component/system.

## Architecture
- **Purpose:**
- **Dependencies:**
- **Integration Points:**

## Implementation
### Key Components
### Configuration
### Deployment

## Testing
## Monitoring
## Troubleshooting

## References
EOF

# Runbook Template
cat <<'EOF' > "$VAULT_ROOT/90_Admin/Templates/Runbook.md"
---
created: {{date}}
tags: [#type/runbook, #domain/xxx]
severity: low|medium|high|critical
---

# Runbook: {{title}}

## Prerequisites
- [ ] Item 1

## Execution Steps
### Step 1
### Step 2

## Verification
## Rollback Plan
## Troubleshooting

EOF

success "Templates created."

# --- 4. Process Projects ---
log "Processing source projects..."

for entry in "${PROJECTS[@]}"; do
    read -r target_name source_dir <<< "$entry"
    target_path="$VAULT_ROOT/10_Projects/$target_name"
    source_path="$SOURCE_ROOT/$source_dir"

    mkdir -p "$target_path"

    if [ -d "$source_path" ]; then
        # Create README
        if [ -f "$source_path/README.md" ]; then
            cat > "$target_path/README.md" <<EOREADME
---
type: project-index
source: $source_path
generated: $(date +%Y-%m-%d)
tags: [#project/$(echo $source_dir | tr '-' '/')]
---

# $target_name

**Source Repository:** \`$source_path\`

---

EOREADME
            cat "$source_path/README.md" >> "$target_path/README.md"
            success "Imported README for $target_name"
        else
            cat > "$target_path/README.md" <<EOREADME
---
type: project-index
source: $source_path
generated: $(date +%Y-%m-%d)
---

# $target_name

**Source Repository:** \`$source_path\`

*No README found in source repository.*

EOREADME
        fi
    else
        echo "⚠️  Warning: Source $source_path not found."
    fi
done

# --- 5. Create Domain Indices ---
log "Building Domain Indices..."

cat <<'EOF' > "$VAULT_ROOT/20_Domains/README.md"
---
tags: [#type/index]
---

# Knowledge Domains

Cross-project knowledge and best practices.

## Domains

- [[21_Audio_Engineering/README|Audio Engineering]] - Signal flow, mixing, mastering
- [[22_AI_Systems/README|AI Systems]] - LLMs, agents, automation
- [[23_DevOps/README|DevOps]] - Docker, CI/CD, deployment
- [[24_Business_Admin/README|Business & Admin]] - Operations, finances

---

**Related:** [[00_Atlas/MOCs/MOC_Master|Master MOC]]
EOF

success "Domain indices created."

log "Vault setup complete!"
echo ""
echo "Next steps:"
echo "1. Open Obsidian and select the rhncrs-collab vault"
echo "2. Review the generated structure"
echo "3. Customize templates as needed"
